From leendert@paramecium.org Fri Apr 26 15:08:40 2013
Date: Fri, 26 Apr 2013 14:08:22 +0100
Subject: Re: nfsshell.c
From: Leendert van Doorn <leendert@paramecium.org>
To: Michael Brown <michael@netdirect.ca>,
        Leendert van Doorn <leendert@cs.vu.nl>
Message-ID: <CDA036F4.69CBF%leendert@paramecium.org>
Thread-Topic: nfsshell.c
In-Reply-To: <5179E004.2080805@netdirect.ca>
Mime-version: 1.0
Content-type: text/plain;
	charset="UTF-8"
Content-transfer-encoding: quoted-printable


Hi Michael,

This code preceded BSD and even X11 licenses :) I'm happy to put a BSD
license on it.

I won't be able to do it on the ftp site below (that's my old university
and I don't even have an account there anymore) but I can put it up on my
own ftp site.

	Leendert


On 4/26/13 3:01 AM, "Michael Brown" <michael@netdirect.ca> wrote:

>Hello!
>
>I've come across this[1] and needed to adapt it to my purposes. It now
>supports NFSv3 (or it will after I actually test it).
>
>I'd potentially like to publish my changes. Is the code you posted under
>any sort of license (MIT X11 for example)?
>
>M.
>
>[1] ftp://ftp.cs.vu.nl/pub/leendert/nfsshell.tar.gz
>
>--=20
>Michael Brown               | `One of the main causes of the fall of
>Systems Consultant          | the Roman Empire was that, lacking zero,
>Net Direct Inc.             | they had no way to indicate successful
>=E2=98=8E: +1 519 883 1172 x5106    | termination of their C programs.' - Firth


